apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-website
  labels:
    app: python-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-website
  template:
    metadata:
      labels:
        app: python-website
    spec:
      containers:
      - name: python-website
        image: ramesh4500/my-web-app:v1
        ports:
        - containerPort: 8000