
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: python-website
spec:
  ingressClassName: nginx
  rules:
  - host: "ramesh-webapp.test.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: python-website
            port:
              number: 8080
 